# Generated by Django 2.1.7 on 2019-03-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Количество порций'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_name',
            field=models.CharField(max_length=200, verbose_name='Название ингридиента'),
        ),
    ]
