# Generated by Django 2.1.7 on 2019-03-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190319_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsinorder',
            old_name='weight',
            new_name='count',
        ),
    ]
