# Generated by Django 2.1.7 on 2019-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190319_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientsinorder',
            name='count',
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='menu.Ingredients'),
        ),
    ]
