# Generated by Django 2.1.7 on 2019-03-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20190319_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientsinorder',
            name='count',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Количество порций'),
        ),
    ]
