# Generated by Django 2.1.7 on 2019-03-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20190320_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsinorder',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Количество порций'),
        ),
    ]
